package DauctionApp.DauctionPackage;


/**
* DauctionApp/DauctionPackage/AuctionStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class AuctionStatus implements org.omg.CORBA.portable.IDLEntity
{
  public String user = null;
  public String item = null;
  public float currentPrice = (float)0;

  public AuctionStatus ()
  {
  } // ctor

  public AuctionStatus (String _user, String _item, float _currentPrice)
  {
    user = _user;
    item = _item;
    currentPrice = _currentPrice;
  } // ctor

} // class AuctionStatus
