package DauctionApp.DauctionPackage;


/**
* DauctionApp/DauctionPackage/IncorrectStatusException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectStatusException extends org.omg.CORBA.UserException
{
  public String description = null;

  public IncorrectStatusException ()
  {
    super(IncorrectStatusExceptionHelper.id());
  } // ctor

  public IncorrectStatusException (String _description)
  {
    super(IncorrectStatusExceptionHelper.id());
    description = _description;
  } // ctor


  public IncorrectStatusException (String $reason, String _description)
  {
    super(IncorrectStatusExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class IncorrectStatusException
