package DauctionApp.DauctionPackage;


/**
* DauctionApp/DauctionPackage/IncorrectBidException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectBidException extends org.omg.CORBA.UserException
{
  public String description = null;

  public IncorrectBidException ()
  {
    super(IncorrectBidExceptionHelper.id());
  } // ctor

  public IncorrectBidException (String _description)
  {
    super(IncorrectBidExceptionHelper.id());
    description = _description;
  } // ctor


  public IncorrectBidException (String $reason, String _description)
  {
    super(IncorrectBidExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class IncorrectBidException
