package DauctionApp.DauctionPackage;

/**
* DauctionApp/DauctionPackage/IncorrectSellExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectSellExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DauctionApp.DauctionPackage.IncorrectSellException value = null;

  public IncorrectSellExceptionHolder ()
  {
  }

  public IncorrectSellExceptionHolder (DauctionApp.DauctionPackage.IncorrectSellException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DauctionApp.DauctionPackage.IncorrectSellExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DauctionApp.DauctionPackage.IncorrectSellExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DauctionApp.DauctionPackage.IncorrectSellExceptionHelper.type ();
  }

}
