package DauctionApp.DauctionPackage;

/**
* DauctionApp/DauctionPackage/IncorrectOfferExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectOfferExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DauctionApp.DauctionPackage.IncorrectOfferException value = null;

  public IncorrectOfferExceptionHolder ()
  {
  }

  public IncorrectOfferExceptionHolder (DauctionApp.DauctionPackage.IncorrectOfferException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DauctionApp.DauctionPackage.IncorrectOfferExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DauctionApp.DauctionPackage.IncorrectOfferExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DauctionApp.DauctionPackage.IncorrectOfferExceptionHelper.type ();
  }

}
