package DauctionApp.DauctionPackage;

/**
* DauctionApp/DauctionPackage/IncorrectStatusExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectStatusExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DauctionApp.DauctionPackage.IncorrectStatusException value = null;

  public IncorrectStatusExceptionHolder ()
  {
  }

  public IncorrectStatusExceptionHolder (DauctionApp.DauctionPackage.IncorrectStatusException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DauctionApp.DauctionPackage.IncorrectStatusExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DauctionApp.DauctionPackage.IncorrectStatusExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DauctionApp.DauctionPackage.IncorrectStatusExceptionHelper.type ();
  }

}
