package DauctionApp.DauctionPackage;

/**
* DauctionApp/DauctionPackage/IncorrectBidExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectBidExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DauctionApp.DauctionPackage.IncorrectBidException value = null;

  public IncorrectBidExceptionHolder ()
  {
  }

  public IncorrectBidExceptionHolder (DauctionApp.DauctionPackage.IncorrectBidException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DauctionApp.DauctionPackage.IncorrectBidExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DauctionApp.DauctionPackage.IncorrectBidExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DauctionApp.DauctionPackage.IncorrectBidExceptionHelper.type ();
  }

}
