package DauctionApp.DauctionPackage;


/**
* DauctionApp/DauctionPackage/IncorrectSellException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public final class IncorrectSellException extends org.omg.CORBA.UserException
{
  public String description = null;

  public IncorrectSellException ()
  {
    super(IncorrectSellExceptionHelper.id());
  } // ctor

  public IncorrectSellException (String _description)
  {
    super(IncorrectSellExceptionHelper.id());
    description = _description;
  } // ctor


  public IncorrectSellException (String $reason, String _description)
  {
    super(IncorrectSellExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class IncorrectSellException
