package DauctionApp.DauctionPackage;


/**
* DauctionApp/DauctionPackage/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/


//methods
abstract public class StatusHelper
{
  private static String  _id = "IDL:DauctionApp/Dauction/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, DauctionApp.DauctionPackage.AuctionStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DauctionApp.DauctionPackage.AuctionStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DauctionApp.DauctionPackage.AuctionStatusHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (DauctionApp.DauctionPackage.StatusHelper.id (), "Status", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DauctionApp.DauctionPackage.AuctionStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    DauctionApp.DauctionPackage.AuctionStatus value = null;
    value = DauctionApp.DauctionPackage.AuctionStatusHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DauctionApp.DauctionPackage.AuctionStatus value)
  {
    DauctionApp.DauctionPackage.AuctionStatusHelper.write (ostream, value);
  }

}
