package DauctionApp;


/**
* DauctionApp/DauctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

public interface DauctionOperations 
{
  boolean offer_item (String item_name, String seller_id, float init_price) throws DauctionApp.DauctionPackage.IncorrectOfferException;
  String view_high_bidder (String item_name) throws DauctionApp.DauctionPackage.IncorrectSellException;
  boolean sell (String item_name) throws DauctionApp.DauctionPackage.IncorrectSellException;
  boolean bid (String user_id, float offer_price) throws DauctionApp.DauctionPackage.IncorrectBidException;
  String view_bid_status (String user_id) throws DauctionApp.DauctionPackage.IncorrectBidException;
  DauctionApp.DauctionPackage.AuctionStatus view_auction_status () throws DauctionApp.DauctionPackage.IncorrectStatusException;
} // interface DauctionOperations
