package DauctionApp;


/**
* DauctionApp/DauctionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dauction.idl
* Tuesday, April 5, 2016 2:04:37 PM CDT
*/

abstract public class DauctionHelper
{
  private static String  _id = "IDL:DauctionApp/Dauction:1.0";

  public static void insert (org.omg.CORBA.Any a, DauctionApp.Dauction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DauctionApp.Dauction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DauctionApp.DauctionHelper.id (), "Dauction");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DauctionApp.Dauction read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DauctionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DauctionApp.Dauction value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DauctionApp.Dauction narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DauctionApp.Dauction)
      return (DauctionApp.Dauction)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DauctionApp._DauctionStub stub = new DauctionApp._DauctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DauctionApp.Dauction unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DauctionApp.Dauction)
      return (DauctionApp.Dauction)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DauctionApp._DauctionStub stub = new DauctionApp._DauctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
